# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    # service conatiners to run with 'container-job'
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: billi_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install golang-migrate
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin/migrate
       which migrate
    
    - name: Create app.env
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> app.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> app.env
        echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
        echo "DB_DRIVER=postgres" >> app.env
        echo "SERVER_ADDRESS=0.0.0.0:8080" >> app.env
    
    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
